services:
  web:
    build: .
    ports:
      - "80:80"
      - "3307:3306"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: silver_happy
      DB_USER: sh_user
      DB_PASS: ChoisisUnMotDePasseFort
      JWT_SECRET: silverhappy_secret_jwt_2026_ovh
    restart: always

  db:
    image: mariadb:10.11
    environment:
      MYSQL_ROOT_PASSWORD: rootsecret
      MYSQL_DATABASE: silver_happy
      MYSQL_USER: sh_user
      MYSQL_PASSWORD: ChoisisUnMotDePasseFort
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  go-api:
    build: ./go-api
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_NAME: silver_happy
      DB_USER: sh_user
      DB_PASS: ChoisisUnMotDePasseFort
      JWT_SECRET: silverhappy_secret_jwt_2026_ovh
    depends_on:
      - db
    restart: always

  # phpMyAdmin : interface bdd sur http://51.210.12.40:8081
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: sh_user
      PMA_PASSWORD: ChoisisUnMotDePasseFort
      UPLOAD_LIMIT: 50M
    depends_on:
      - db
    restart: always

volumes:
  db_data:

  environment:
  STRIPE_PUBLIC_KEY: "${STRIPE_PUBLIC_KEY}"
  STRIPE_SECRET_KEY: "${STRIPE_SECRET_KEY}"
  STRIPE_SECRET: "${STRIPE_SECRET}"